export const swaggerConfig = {
  openapi:"3.0.0",
  info:{
    title:'Survey API',
    version:'1.0.0',
    description:'Esta API llamada survey permite generan encuestas por medio de preguntas abierta y/o cerradas y a su vez descargarlas en formato pdf.',
    contact: {
      name: 'Neider Lopez',
      email: 'neider86@protonmail.com'
    }
  },
  servers:[
    {
      url:'http://localhost:3000/v1'
    }
  ],
  tags: [
    {
      name: 'Surveys',
      description: 'Survey EndPoints' 
    }
  ],
  /* COMPONENTES REUTILIZABLES */
  components:{
    schemas:{
      Survey: {
        type: 'object',
        properties: {
          id:{
            type: 'string',
            description: 'Survey id Autogenerated',
            example: '638f98822903d2b9dccc7474'
          },
          titleSurvey: {
            type: 'string',
            description: 'Title survey',
            example: 'Lenguajes de programacion con mas demanda 2022'
          },
          description:{
            type: 'string',
            description: 'Description survey',
            example: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua'
          },
          question:{
            type: 'array',
            items: {
              type: 'object',
              properties: {
                titleQuestion: {
                  type: 'string',
                  description: 'string',
                  example: 'Que proyectos haz realizado con TypeScript'
                },
                typeQuestion:{
                  type: 'string',
                  description: 'Type question QUESTION_OPEN or QUESTION_MULTIPLE',
                  example: 'QUESTION_OPEN'
                },
                answerO:{
                  type: 'string',
                  description:'Answer question open (QUESTION_OPEN)',
                  example: 'Duis aute irure dolor in reprehenderit in voluptate'
                },
                answerM: {
                  type: 'object',
                  properties:{
                    options:{
                      type: 'array',
                      items:{
                        type: 'string',
                        example: 'JQUERY',
                      }
                    },
                    answer: {
                      type: 'string',
                      example: 'HELLO WORLD'
                    }
                  }
                }
              }
            }
          },
          createAt:{
            type: 'string',
            description: 'Survey creation date',
            example: '2022-12-06T19:28:26.890Z'
          },
          state:{
            type: 'string',
            description: 'If true, the survey is active',
            example: true
          }
        },
        required:[
          'id','titleSurvey'
        ]
      },
      SurveyNotFound:{
        type: 'object',
        properties:{
          message:{
            type: 'string',
            description: 'Survey was not found'
          }
        },
        example:{
          message: 'Survey was not found'
        }
      },
      QuestionNotFound:{
        type: 'object',
        properties:{
          message:{
            type: 'string',
            description: 'Question was not found',
          }
        },
        example:{
          message: 'Question was not found'
        }
      }
    },
    parameters:{
      surveyId: {
        name: 'id', 
        in:'path',
        description: 'Id from survey',
        required: true,
        schema:{
          type: 'string'
        }
      },
      surveyID: {
        name: 'idSurvey', 
        in:'path',
        description: 'Id from survey',
        required: true,
        schema:{
          type: 'string'
        }
      },
      questionID: {
        name: 'idQuestion', 
        in:'path',
        description: 'Id from question',
        required: true,
        schema:{
          type: 'string'
        }
      }
    }
  },
 /* DIFERENTES RUTAS DE LA API REST*/
 // OBTENER TODAS LAS ENCUESTAS
  paths: {
    "/surveys": {
      get: {
        summary: 'Return all surveys',
        tags: ["Surveys"],
        responses: {
          '200': {
            description: 'Lists of surveys',
            content: {
              "application/json":{
                schema: {
                  type: 'array',
                  items: {
                    $ref: '#/components/schemas/Survey'
                  }
                }
              }
            }
          },
          '500':{
            description:'Error in the server',
            content: {
              "application/json":{
                schema: {
                  $ref: '#/components/schemas/SurveyNotFound'
                }
              }
            }
          }
        }
      }
    },
    /* OBTENER UNA ENCUESTA POR ID */
    "/survey/{id}":{
      get: {
        summary: 'Get one survey by ID',
        tags: ['Surveys'],
        parameters: [
          {
            $ref: '#/components/parameters/surveyId'
          }
        ],
        responses:{
          '200':{
            description: 'Survey was found',
            content: {
              "application/json":{
                schema: {
                  type: 'array',
                  items: {
                    $ref: '#/components/schemas/Survey'
                  }
                }
              }
            }
          },
          '500':{
            description:'Error in the server',
            content: {
              "application/json":{
                schema: {
                  $ref: '#/components/schemas/SurveyNotFound'
                }
              }
            }
          }
        }
      },
      /* ACTUALIZAR UNA ENCUESTA */
      put: {
        summary: 'Update survey',
        tags: ['Surveys'],
        parameters:[
          {
            $ref: '#/components/parameters/surveyId'
          }
        ],
        requestBody:{
          required:true,
          content:{
            'application/json':{
              schema:{
                $ref:'#/components/schemas/Survey'
              }
            }
          }
        },
        responses:{
          '200':{
            description: 'Survey update',
            content: {
              "application/json":{
                schema: {
                  $ref: '#/components/schemas/Survey'
                }
              }
            }
          },
          '500':{
            description:'Error in the server',
            content: {
              "application/json":{
                schema: {
                  $ref: '#/components/schemas/SurveyNotFound'
                }
              }
            }
          }
        }
      },
      /* ELIMINAR UNA ENCUESTA */
      delete: {
        summary: 'Delete survey by ID',
        tags: ['Surveys'],
        parameters:[
          {
            $ref: '#/components/parameters/surveyId'
          }
        ],
        responses:{
          '200':{
            description: 'Survey was delete successfully',
            content: {
              "application/json":{
                schema: {
                  $ref: '#/components/schemas/Survey'
                }
              }
            }
          },
          '500':{
            description:'Error in the server',
            content: {
              "application/json":{
                schema: {
                  $ref: '#/components/schemas/SurveyNotFound'
                }
              }
            }
          }
        }
      }
    },
    /* OBTENER UNA PREGUNTA DE UNA ENCUESTA */
    "/survey/{idSurvey}/{idQuestion}": {
      get: {
        summary: 'Get a question from a survey',
        tags: ['Surveys'],
        parameters:[
          {
            $ref: '#/components/parameters/surveyID'
          },
          {
            $ref: '#/components/parameters/questionID'
          }
        ],
        responses:{
          '200':{
            description: 'Question was found',
            content: {
              "application/json":{
                schema: {
                  $ref: '#/components/schemas/Survey'
                }
              }
            }
          },
          '500':{
            description:'Error in the server',
            content: {
              "application/json":{
                schema: {
                  $ref: '#/components/schemas/QuestionNotFound'
                }
              }
            }
          }
        }
      },
      /* ELIMINAR UNA PREGUNTA DE UNA ENCUESTA */
      'delete':{
        summary:'Delete a question from a survey',
        tags:['Surveys'],
        parameters:[
          {
            $ref: '#/components/parameters/surveyID'
          },
          {
            $ref:'#/components/parameters/questionID'
          }
        ],
        responses:{
          '200':{
            description: 'Delete a question from a survey',
            content: {
              "application/json":{
                schema:{
                  $ref: '#/components/schemas/Survey'
                }
              }
            }
          },
          '500':{
            description:'Server error',
            content:{
              "application/json":{
                schema:{
                  $ref:'#/components/schemas/QuestionNotFound'
                }
              }
            }
          }
        }
      }
    },
    '/survey':{
      post:{
        summary: 'Create new survey',
        tags: ['Surveys'],
        requestBody: {
          description: 'lorem ipsum dolir voluptate',
          required: true,
          content: {
            'application/json':{
              schema: {
                $ref: '#/components/schemas/Survey'
              }
            }
          }
        },
        responses:{
          '201':{
            description: 'Survey created succcesfully',
            content:{
              'application/json':{
                schema: {
                  $ref: '#/components/schemas/Survey'
                }
              }
            }
          },
          '500':{
            description: 'Server error'
          }
        }
      }
    },
    /* ACTUALIZAR UNA PREGUNTA DE UNA ENCUESTA - Responder una pregunta */
    '/sub-question/{id}/{idQuestion}':{
      put:{
        summary: 'Update a question from a survey - Answer a question',
        tags: ['Surveys'],
        parameters:[
          {
            $ref: '#/components/parameters/surveyId'
          },
          {
            $ref: '#/components/parameters/questionID'
          }
        ],
        requestBody:{
          required: true,
          content:{
            'application/json':{
              schema:{
                $ref: '#/components/schemas/Survey'
              }
            }
          }
        },
        responses:{
          '200':{
            description: 'Question was found',
            content:{
              'application/json':{
                schema: {
                  $ref: '#/components/schemas/Survey'
                }
              }
            }
          },
          '404': {
            description: 'Dont exist question with this ID',
            content:{
              'application/json':{
                schema: {
                  $ref: '#/components/schemas/Survey'
                }
              }
            }
          },
          '500':{
            description: 'Server error',
            content: {
              'application/json':{
                schema: {
                  $ref: '#/components/schemas/QuestionNotFound'
                }
              }
            }
          }
        }
      }
    },
    /* ACTUALIZAR LAS OPCIONES DE UNA PREGUNTA tipo OPTION_MULTIPLE QUE PERTENECE A UNA ENCUESTA */
    '/question/option/{id}/{idQuestion}':{
      put: {
        summary:'Actualizar las opciones de una pregunta tipo QUESTION_MULTIPLE',
        tags: ['Surveys'],
        parameters:[
          {
            $ref: '#/components/parameters/surveyId'
          },
          {
            $ref: '#/components/parameters/questionID'
          }
        ],
        requestBody:{
          required: true,
          content:{
            'application/json':{
              schema:{
                $ref: '#/components/schemas/Survey'
              }
            }
          }
        },
        responses:{
          '200':{
            description: 'Question was found',
            content:{
              'application/json':{
                schema: {
                  $ref: '#/components/schemas/Survey'
                }
              }
            }
          },
          '404': {
            description: 'Dont exist question with this ID',
            content:{
              'application/json':{
                schema: {
                  $ref: '#/components/schemas/Survey'
                }
              }
            }
          },
          '500':{
            description: 'Server error',
            content: {
              'application/json':{
                schema: {
                  $ref: '#/components/schemas/QuestionNotFound'
                }
              }
            }
          }
        }
      }
    },
    /* AGREGAR UNA PREGUNTA A UNA ENCUESTA */
    '/push-question/{idSurvey}':{
      put: {
        summary: 'Add a question to the survey',
        tags: ['Surveys'],
        parameters:[
          {
            $ref: '#/components/parameters/surveyID'
          }
        ],
        requestBody:{
          required: true,
          content: {
            'application/json':{
              schema: {
                $ref: '#/components/schemas/Survey'
              }
            }
          }
        },
        responses:{
          '200':{
            description: 'Question was found',
            content:{
              'application/json':{
                schema: {
                  $ref: '#/components/schemas/Survey'
                }
              }
            }
          },
          '500':{
            description: 'Server error',
            content: {
              'application/json':{
                schema: {
                  $ref: '#/components/schemas/QuestionNotFound'
                }
              }
            }
          }
        }
      }
    }
  }
}